export const darkTheme = {
  colors: {
    background: '#131315',
    surface: '#131315',
    'surface-dim': '#131315',
    'surface-container-lowest': '#0e0e10',
    'surface-container-low': '#1c1b1d',
    'surface-container': '#201f22',
    'surface-container-high': '#2a2a2c',
    'surface-container-highest': '#353437',
    'surface-bright': '#39393b',
    'surface-variant': '#353437',
    'on-background': '#e5e1e4',
    'on-surface': '#e5e1e4',
    'on-surface-variant': '#c3c5d7',
    primary: '#a4c9ff',
    'primary-container': '#0062b1',
    'primary-fixed': '#d4e3ff',
    'primary-fixed-dim': '#a4c9ff',
    'on-primary': '#00315d',
    'on-primary-container': '#cbdeff',
    'on-primary-fixed': '#001c39',
    'on-primary-fixed-variant': '#004883',
    secondary: '#cebdff',
    'secondary-container': '#4f319c',
    'secondary-fixed': '#e8ddff',
    'secondary-fixed-dim': '#cebdff',
    'on-secondary': '#381385',
    'on-secondary-container': '#bea8ff',
    'on-secondary-fixed': '#21005e',
    'on-secondary-fixed-variant': '#4f319c',
    tertiary: '#45dfa4',
    'tertiary-fixed': '#68fcbf',
    'tertiary-fixed-dim': '#45dfa4',
    'tertiary-container': '#006f4d',
    'on-tertiary': '#003825',
    'on-tertiary-container': '#61f6b9',
    'on-tertiary-fixed': '#002114',
    'on-tertiary-fixed-variant': '#005137',
    'inverse-primary': '#0060ac',
    'inverse-surface': '#e5e1e4',
    'inverse-on-surface': '#313032',
    'surface-tint': '#a4c9ff',
    outline: '#8d90a0',
    'outline-variant': '#434654',
    error: '#ffb4ab',
    'error-container': '#93000a',
    'on-error': '#690005',
    'on-error-container': '#ffdad6',
  },
  isDark: true,
};

export const lightTheme = {
  colors: {
    background: '#ffffff',
    surface: '#fdf8fd',
    'surface-container-low': '#f7f2f7',
    'surface-container': '#f1ecf1',
    'surface-container-high': '#ebe6eb',
    primary: '#0060ac',
    'on-primary': '#ffffff',
    'primary-container': '#d4e3ff',
    secondary: '#5c3f9e',
    'on-secondary': '#ffffff',
    tertiary: '#006c4a',
    'on-surface': '#1c1b1e',
    'on-surface-variant': '#46464f',
    outline: '#777680',
    'outline-variant': '#c7c5d0',
  },
  isDark: false,
};

export const typography = {
  displayLarge: { fontFamily: 'Inter', fontWeight: '300', fontSize: 57 },
  headlineLarge: { fontFamily: 'Inter', fontWeight: '300', fontSize: 32 },
  headlineMedium: { fontFamily: 'Inter', fontWeight: '600', fontSize: 28 },
  titleLarge: { fontFamily: 'Inter', fontWeight: '600', fontSize: 22 },
  titleMedium: { fontFamily: 'Inter', fontWeight: '500', fontSize: 16 },
  bodyLarge: { fontFamily: 'Inter', fontWeight: '400', fontSize: 16, lineHeight: 24 },
  bodyMedium: { fontFamily: 'Inter', fontWeight: '400', fontSize: 14, lineHeight: 20 },
  bodySmall: { fontFamily: 'Inter', fontWeight: '400', fontSize: 12, lineHeight: 16 },
  labelLarge: { fontFamily: 'Inter', fontWeight: '500', fontSize: 14 },
  labelMedium: { fontFamily: 'Inter', fontWeight: '500', fontSize: 12 },
  labelSmall: { fontFamily: 'Inter', fontWeight: '500', fontSize: 11 },
  monoBody: { fontFamily: 'JetBrains Mono', fontWeight: '400', fontSize: 14 },
  monoLabel: { fontFamily: 'JetBrains Mono', fontWeight: '500', fontSize: 12 },
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  huge: 48,
  massive: 64,
  safeTop: 24,
  safeBottom: 32,
};

export const borderRadius = {
  extraSmall: 4,
  small: 8,
  medium: 12,
  large: 16,
  extraLarge: 28,
  full: 9999,
};

export const shadows = {
  floating: (isDark) => ({
    shadowColor: isDark ? darkTheme.colors.primary : lightTheme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 32,
    elevation: 8,
  }),
};
